FROM tomcat:10.0
WORKDIR /app
COPY . /app
RUN ./mvnw package -DskipTests
RUN echo "copying war files from /app/target to /usr/local/tomcat/webapps/"
RUN cp /app/sample.war /usr/local/tomcat/webapps/
EXPOSE 8080
CMD ["catalina.sh", "run"]

#RUN cp /app/target/dockerforjava-0.0.1-SNAPSHOT.war /usr/local/tomcat/webapps/
#COPY ./target/*.war /usr/local/tomcat/webapps/
#ADD /target/*.war /usr/local/tomcat/webapps/

#https://tecadmin.net/deploy-java-war-docker/
